### ISSUE TITLE
Openstack instance not getting the ip

### ISSUE THREAD

**Issue by pawanku2** [phiche/vagrant-puppet-openstack#1]
I have followed your puppet-openstack trouble shooting steps.My compute node got the tcpdump packet while doing dhcp discover from instance. But Network node didnt get any packet . My instance didn't get the Ip. I have tried to set the ip manully but still not able to ping the gateway and /etc/resolv.conf also didnt have any entries. no route have been created. Can you give some pointer what might be the issue?

**Comment by philbert** [comment]
Sorry for the late reply. I was on vacation. 

Can you confirm with me that you performed step 10 in the readme?

**Comment by pawanku2** [comment]
yes i have tried the 10 step of readme but no success.I am attaching the
logs and config file . Instance not getting the IP Even though i can see
the tcpdump on br-int of compute node and neutron node.I can able to see
DHCPDISCOVER and DHCPOFFER in syslog. But DHCPOFFER not reach to VM
instance.How to analyze where the return packet drop?

**Comment by philbert** [comment]
You must have made some progress if you are seeing DHCP-Offers now at least.

Can you tell me what is your Operating System and Vagrant and Virtualbox versions?

**Comment by pawanku2** [comment]
I am using dell server , on dell server i have installed ECS Hypervisor
 and created virtual machines. On each virtual machine i have installed
ubuntu 14.04. so i have three machine for Controller, Compute and neutron.
On each Machine i have two interface eth0 and eth1. eth0 for API/PUBLIC/
 and eth1 is using for Management Network.

**Comment by philbert** [comment]
Sorry I'm not familiar with that hypervisor? That's a very different configuration than what I worked with in this setup.

The best I can do for you is direct you to this page to troubleshoot neutron networking: http://docs.openstack.org/openstack-ops/content/network_troubleshooting.html
